name: flutter_iot_application
description: flutter_iot_application
version: 1.0.0+1
publish_to: 'none'
environment:
  sdk: ">=2.14.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.2
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  cloud_firestore: ^6.1.1
  flutter_easyloading: ^3.0.5
  http: ^1.1.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  firebase_storage: ^13.0.5
  cached_network_image: ^3.4.1
  smooth_page_indicator: ^2.0.1
  the_apple_sign_in: ^1.1.1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^16.2.0
  overlay_support: ^2.1.0



flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: android/app/src/main/ic_launcher-playstore.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/